schoold/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to: "home#index"

get "profile" => "home#profile", as: "profile"

get "/users/:id" => "users#profile", as: "user_profile"


get "/challenge_one", to: "challenges#profile_picture"
post "/challenge_one", to: "challenges#profile_picture"

get "/challenge_two", to: "challenges#heading"
post "/challenge_two", to: "challenges#heading"

get "/challenge_three", to: "challenges#about"
post "/challenge_three", to: "challenges#about"

get "/challenge_four", to: "challenges#gallery"
post "/challenge_four", to: "challenges#gallery"

get "/challenge_five", to: "challenges#video"
post "/challenge_five", to: "challenges#video"

get "/css_challenge_1", to: "challenges#background"
get	"/css_challenge_2", to: "challenges#picture_positioning"
get	"/css_challenge_3", to: "challenges#layout"
get	"/css_challenge_4", to: "challenges#typography"
get	"/css_challenge_5", to: "challenges#styling"
end

schoold/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

schoold/app/models/challenge.rb
class Challenge < ApplicationRecord
	belongs_to :user
end

schoold/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 
end

schoold/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

schoold/app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
<<<<<<< HEAD
	before_action :set_challenge, only: [:update_heading, :update_paragraph, :update_image_one, :update_image_two, :update_image_three, :update_video_tag]

=======
	def profile_picture
	 HEAD
		@challenge = Challenge.new(challenge_params)
		@user = User.find(current_user)
	 end
>>>>>>> 5bd73c2f0e536a72273079d09841f4e2f46b8e1c


	def update_profile
		@challenge = Challenge.create(profile_pic: "")
		@challenge = challenge.update(profile_pic: params[:profile_pic])

	 	 if @challenge.save
	 	 	format.html { redirect_to "/challenge_two" }
	 	 end
	 end

	 def update_heading
	 	@challenge = challenge.update(heading_tag: params[:heading_tag])
	 end

	 def update_paragraph 
	 	@challenge = challenge.update(p_tag: params[:p_tag])
	 end


	 def update_image_one 
	 	@challenge = challenge.update(image_one: params[:image_one])
	 end


	 def update_image_two 
	 	@challenge = challenge.update(image_two: params[:image_two])
	 end


	 def update_image_three
	 	@challenge = challenge.update(image_three: params[:image_three])
	 end


	 def update_video_tag 
	 	@challenge = challenge.update(video_tag: params[:video_tag])
	 end

<<<<<<< HEAD


	private

	def set_challenge
		@challenge = Challenge.find(1)
	end 
=======
	 private 
>>>>>>> 5bd73c2f0e536a72273079d09841f4e2f46b8e1c
	 
	 def challenge_params
	 	params.require(:challenge).permit(:profile_pic, :heading_tag, :p_tag, :image_one, :image_two, :image_three, :video_tag)
	 end
<<<<<<< HEAD
end
=======
>>>>>>> 5bd73c2f0e536a72273079d09841f4e2f46b8e1c

schoold/app/controllers/home_controller.rb
class HomeController < ApplicationController
end

schoold/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	private

		def sign_up_params
			params.require(:user).permit(:email, :password, :password_confirmation, :avatar)
		end
end

schoold/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def profile
		@user = User.find(params[:id])
	end
end

schoold/app/helpers/application_helper.rb
module ApplicationHelper
end

schoold/app/helpers/challenges_helper.rb
module ChallengesHelper
end

schoold/app/helpers/games_helper.rb
module GamesHelper
end

schoold/app/helpers/home_helper.rb
module HomeHelper
end

schoold/app/helpers/registrations_helper.rb
module RegistrationsHelper
end

schoold/app/helpers/users_helper.rb
module UsersHelper
end

schoold/app/views/challenges/about.html.erb
<div class="row">

	<div class="col-md-6">
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
		<div class="challenge">
		<p class="challenge-description">We've now got ourselves a profile picture and your name. Almost enough to really make it your own. Now we're going to use the paragraph, or "p" tag to enter in an about me. You can type any amount inside the text field because a "p" tag can hold a huge amount of text!
		</p>


		
		<a class="links" href="https://www.w3schools.com/tags/tag_p.asp">W3chools definition of a "p" tag</a>
	

	<!-- 	<p class="picture-input">"< p >"</p><input type="text" name="p_tag" id="answer3" /><p>"< / p >"</p>	
		<button type="button">Submit code!</button>
		<button type="submit" ></button> -->
		

		<%= form_for :p_tag do |f| %>
			<p> < p >
			<%= f.text_area :p_tag, id: "answer3" %>
			< /p >									</p>
			<button type="button">Submit Code!</button>
			<%= f.submit "Next Challenge!" %>
			<a href="/challenge_four">Next Challenge</a>
		<% end %>

		</div>


	</div>

	<div class="col-md-6">

	<div class="custom_background">
			<img class="profile-picture" src="">
						<h1 class="heading_tag">Domitrius Clark</h1>

			
			<p id="about"></p>

			</div>
			</div>

	</div>

schoold/app/views/challenges/background.html.erb
<div class="row">

	<div class="col-md-6">

		<p class="challenge_description">
			The default background in any browser is always set to a bare and boring white.  Sometimes the developer will style the background through the body element, thus making all the pages the same color and style.  This is known as a layout style.  In our case, the background has been set to a tone of silver.  Yet, if we wanted to, we could customize the background to any color or colors we want.  So, for this exercise, simply choose a color, type it between the curly braces, and press Submit Code!
		</p>

		<a class= "links" href= https://www.w3schools.com/css/css_intro.asp > Everything you wanted to know about CSS, but were afraid to ask! </a>
<br>
<br>
		<p class="challenge_layout">.custom_background { <br> background-color:</p>
	        <input type="text" name="background_color" id="answer" />
	        <button class = "code_generator" type="button">Submit code!
	        </button>
		<p class="challenge_layout">};</p>
	</div>

	<div class="col-md-6">
		<div class = "custom_background"></div>
	</div>

</div>

schoold/app/views/challenges/gallery.html.erb
<div class="row">

	<div class="col-md-6">
		<div class="challenge">
		<p class="challenge-description">Remember that image tag? Well let's revisit that real quick. This time we're going to be using three images to create a mini gallery of pictures. Go and grab some pictures of your favorite sport, videogame, or whatever you like! (remember you can google your image and copy the URL right into the form!)</p>
		
		<a class="links" href="https://www.w3schools.com/tags/tag_img.asp">W3schools definition and usage of < img > tags</a>

		</div>

		<%= form_for :image_one do |f| %>
			<p>< img ><%= f.text_field  :image_one, id: "answer4" %>< /img ></p>
			<button type="button">Submit Code!</button>
		<% end %>


		<%= form_for :image_two do |f| %>
			<%= f.text_field :image_two, id: "answer5" %>
			<button type="button">Submit Code!</button>
		<% end %>


		<%= form_for :image_three do |f| %>
			<%= f.text_field  :image_three, id: "answer6" %>
			<button type="button">Submit Code!</button>
			<%= f.submit "Next Challenge!" %>
			<a href="/challenge_five">Next Challenge</a>
		<% end %>


	</div>

	<div class="col-md-6">

		<div class="custom_background">
	

		<div class="profile_picture">

			<img class="profile-picture" src="">
		
			<h1 class="heading_tag">Domitrius Clark</h1>
	
			<p id="about"></p>
		<img src="" class="photo-1">
		<img src="" class="photo-2">
		<img src="" class="photo-3">


			<img src="" class="photo-1">
			<img src="" class="photo-2">
			<img src="" class="photo-3">
		</div>			
			</div>
		

			
=======
		</div>		
>>>>>>> 5bd73c2f0e536a72273079d09841f4e2f46b8e1c
	</div>
</div>

schoold/app/views/challenges/heading.html.erb
<div class="row">

	<div class="col-md-6 first-column">
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>	

		<div class="challenge">
		<p class="challenge-description">
		For this challenge we're gonna look into the <i>header</i> tag. There h tags range from h1; the biggest header, to h6; the smallest header. These tags allow you to pull attention to a line of text and show importance! For the purpose of building a profile, we're going to use the h1 tag and enter your name.</p>


		
		<a class="links" href="https://www.w3schools.com/tags/tag_hn.asp">W3schools definition and usage for H1-H6 tags</a>
		

		<!-- <p class="picture-input">"< h1 >"</p><input type="text" name="heading_tag" id="answer2" /><p>"< / h1 >"</p>	
		<button type="button">Submit code!</button>
 -->


		<%= form_for :heading_tag do |f| %>
			<p>< h1 ><%= f.text_field  :heading_tag, id: "answer2" %>< /h1 ></p>
			<button type="button">Submit Code!</button>
			<%= f.submit "Next Challenge!" %>
			<a href="/challenge_three">Next Challenge</a>
		<% end %>


		</div>


	</div>

	<div class="col-md-6">

	<div class="custom_background">


		<img class="profile-picture" src="">
		<h1 class="heading_tag"></h1>

	</div>
		
	</div>








</div>

schoold/app/views/challenges/layout.html.erb
<div class="row">

	<div class="col-md-6">

		<p class="challenge_description">
			Layout styles allow us to layout the page and it's elements in any way we choose.  For instance, do we want the text aligned left, right , or center?  Do we want a lot of space between elements or very little?  This will all be decided in the layout of the page using CSS.
<br>
<br>
			In this exercise we're going to move the content of our profiles around until we have them looking their very best.  We'll do this using the margin and passing properties.  In addition, we'll also align the text we put on our page through the use of text-align.
<br>
<br>
			Manipulating the padding and margin is easy.  Margin will move whatever element we target however many pixels we choose away from it's neighbors.  So, if we add a 10px margin, our text will be spaced 10 pixels away from any other element.  10px of padding will move the text 10 pixels away from the edge of it's own container.  0 padding is like a rug that completely covers a room, while a 10px padding will add 10 pixels of space between the rug and all the walls in the room.  Margin will add space between the rooms in the house.  Text-align will simply move the text left, right, or center by entering one of these three commands.  Let's move some text and Submit Code!
		</p>

		<a class= "links" href= https://www.w3schools.com/css/css_intro.asp > Everything you wanted to know about CSS, but were afraid to ask! </a>
<br>
<br>
	<form method = "get">
		<p class="challenge_layout">.main_content { <br> margin:</p>
      <input type="text" name="margin" id="answer_1" />
    <p class="challenge_layout">.main_content { <br> padding:</p>
      <input type="text" name="padding" id="answer_2" />
    <p class="challenge_layout">.main_content { <br> text-align:</p>
      <input type="text" name="text-align" id="answer_3" />
      <button class = "code_generator" type="button">Submit code!
      </button>
  </form>
		<p class="challenge_layout">};</p>
	</div>

	<div class="col-md-6">
		<div class = "custom_background">
			<p class = "main_content">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>
	</div>

</div>

schoold/app/views/challenges/picture_positioning.html.erb
<div class="row">

	<div class="col-md-6">

		<p class="challenge_description">
			Now we will continue to build on what we learned in the first HTML challenge when we uploaded our profile pictures. This time we will learn how to position, size, and format <img> elements. We will now determine exactly how and where we want our profile pictures to render so that they look exactly how we wanrt them to for anyone who decides to come check out our page.  We can manipulate the position of elements on the page throught the margin property.  Below you'll see the element on the page that represents the profile picture you uploaded earlier followed by a set of curly braces {}.  Inside the curly braces is where we tell CSS what we want to do with that element.  So, we have a margin property and now we'll use that property to center our profile picture.  To do this we simply type 0 auto and voila!  The picture will center before our very eyes in the view on the left.
		</p>

		<a class= "links" href= https://www.w3schools.com/css/css_intro.asp > Everything you wanted to know about CSS, but were afraid to ask! </a>
<br>
<br>
<p class="picture_positioning">.profile_picture { <br> margin:</p>
        <input type="text" name="profile_pic" id="answer" />
        <button class = "code_generator" type="button">Submit code!
        </button>
<p class="picture_positioning">};</p>
	</div>

	<div class="col-md-6">
		<div class="profile_picture"></div>
	</div>

schoold/app/views/challenges/profile_picture.html.erb
<div class="row">

	<div class="col-md-6">


		<p class="challenge-description">This challenge will start off with adding a profile picture to your profile page. A profile picture is as simple as using an <img> tag inside of the body of your HTML. The image tag will take a source, and that source will be translated into whatever picture you choose! You can use any picture from your computer, but for the purpose of this excercise we will be using an image from the internet. Use any image from the internet as your profile picture. Google your image and copy the URL of the image fhe address bar.</p>

		<a class="links" href="google.com">Words that link to a site</a>
		<a class="links" href="google.com">Words that link to a site</a>

		<%= form_for @challenge do |f| %>
			<%= f.text_field  :profile_pic, id: "answer" %>
			<button type="button">Submit Code!</button>
			<%= f.submit "Next Challenge!" %>
			<a href="/challenge_two">Next Challenge</a>
		<% end %>


	</div>



	<div class="col-md-6">
	<div class="custom_background">
		
	


	
			<img class="profile-picture" src="">

		<div class="pro-pic">
			<img class="profile-picture" src="">

		</div>
	</div>

	</div>

</div>

schoold/app/views/challenges/typography.html.erb
<div class="row">
	<div class="col-md-6">
		<p class="challenge_description">
		The text we have comes with some basic style, color, and sizing by default.  Let's change that!  All we need to do is choose a color, type in a size, and pick a style for everyone to see.

		Choose a style from the following:
			- Georgia
			- Verdana
			- Courier New
			- Lucida Console
		</p>

		<a class= "links" href= https://www.w3schools.com/css/css_intro.asp > Everything you wanted to know about CSS, but were afraid to ask! </a>
<br>
<br>
		<p class="challenge_layout">.custom_background { <br> background-color:</p>
	<form method = "get">
		<p class="challenge_layout">.main_content { <br> font-size:</p>
      <input type="text" name="font-size" id="typography_1" />
    <p class="challenge_layout">.main_content { <br> color:</p>
      <input type="text" name="color" id="typography_2" />
    <p class="challenge_layout">.main_content { <br> font-family:</p>
      <input type="text" name="font-family" id="typography_3" />
      <button class = "code_generator" type="button">Submit code!
      </button>
  </form>
		<p class="challenge_layout">};</p>
	</div>

	<div class="col-md-6">
		<div class = "custom_background">
			<p class = "main_content challenge-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>
	</div>

</div>

schoold/app/views/challenges/video.html.erb
<div class="row">

	<div class="col-md-6">


<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

		<div class="challenge">
		<p class="challenge-description">Lastly, let's add a cool video in to your page from youtube! Head on over to youtube and choose your video. When on the video page, click share and highlight the embed link. It will look like this "https://www.youtube.com/embed/y3UH2gAhwPI" Copy over the embed link to the text box and submit it! Inside your embed link, there are parameters that you can change to affect the height, width, and even if the video will autoplay or not! Definitely get into doing some edits on a seperate editor to see how the changes effect the video display! 
		</p>


		
		<a class="links" href="https://www.w3schools.com/tags/tag_iframe.asp">W3schools describes how to properly use iframe!</a>
		

	<!-- 	<p class="picture-input">"Place your Youtube embed here:"</p><input type="text_area" name="video_tag" id="answer7" />
		<button type="button">Submit code!</button> -->

		<%= form_for :video_tag do |f| %>
			<p>Place your Youtube embed here!</p>		
			<%= f.text_area  :video_tag, id: "answer7" %>
			<button type="button">Submit Code!</button>
			<%= f.submit "Next Challenge!" %>
		<% end %>

		</div>


	</div>


	<div class="col-md-6">
	
	<div class="custom_background">



		<img class="profile-picture" src="">
		<h1 class="name"></h1>


		<p id="about"></p>


		<img src="" class="photo-1">
		<img src="" class="photo-2">
		<img src="" class="photo-3">


		<iframe width="560" height="315" class="video" src=""></iframe>
	</div>








</div>

schoold/app/views/games/show.html.erb
  <div class="body">
    <br>
    <br>
    <br>
    <h1 class="header">John S. Occhipinti</h1>
    <div class="profile-pic"></div>
  
  <div class = "music_container">  
    
    <div class="bio">
      <p class = "about-me">About Me</p>
     <br>
      <p class="about">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
      consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
      cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      

      <p class="about">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
      consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
      cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    </div>

    <p class="movies">Movies</p>
      <br>
      <p class="fav-movies">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
      consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
      cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>

    <br>



  <p class="music">Music</p>
  <br>
    <p class="fav-music">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</div>

    <h1 class="photo-gallery">The Photo Gallery</h1>

    <div class="top-gallery">
      <div class="pic-1"></div>
      <div class="pic-2"></div>
      <div class="pic-3"></div>
    </div>

    <div class="bottom-gallery">
      <div class="pic-6"></div>
      <div class="pic-7"></div>
      <div class="pic-8"></div>

    </div>
    
    <div class="audio"><audio class="audio" controls>
    <source src="http://d19bhbirxx14bg.cloudfront.net/mussorgsky-une-larme-alianello.mp3" type="audio/mpeg">
    </audio></div>
    
    <div class="video"><iframe class="video" width="560" height="315" src="https://www.youtube.com/embed/YGOu-raM25k" frameborder="0" allowfullscreen></iframe></div>

  </div>

schoold/app/views/home/index.html.erb
<div class = "primary_background">

<div class="header_holder">
	<h1 class = "header1">Welcome to the future of Learning</h1>
	<h1 class = "sub-header">It's Time to Get School'd</h1>
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

</div>

<div class = "secondary_background">

<br>
<br>
<br>

<h1 class = "header2">The Mission</h1>

<p class = "main-content">School'd is an interactive coding experience dedicated to creating immersive experiences for learning twenty-first century skills through an intuitive and compelling format.  At School'd we believe that learning should not be a chore.  Learning should engage students, it should be wildly entertaining, and above all, it should have a purpose.  Here at School'd we encourage creative risk-taking and fast failure.  Students are not graded.  They are rewarded for trying new things, being creative, being bold, and working collaboratively to solve problems.  It is our goal to see young people empowered by these tools, and then set them loose to shape the world.  <%=link_to "Make an account", new_user_registration_path %> and discover the power of code.</p>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
	</div>

<div class = "tertiary_background">

<br>
<br>
<br>
<br>
<br>
<br>
<br>

<h1 class = "header3">The Design Team</h1>

	<div id = "dom-container">
		<div id = "dom"></div>
		<p class = "bio-content">Domitrius is an up and coming Full Stack developer with a heavy interest in spreading the ability to code for all. He spends most of his free time geeking out on some video games and streaming on Twitch!</p>
	</div>

	<div id = "john-container">
		<div id = "john"></div>
			<p class = "bio-content">My name is John Occhipinti, I was born in Chevy Chase, Maryland to Kerri and John Occhipinti,  my  three older sisters: Jordyn, Taylor, and Riley,  were awaiting my arrival .  After moving to Scranton, Pennsylvania our fifth and final sibling my little sister, Londyn was born.  I enjoy many things including, coding, skiing, and playing basketball.</p>
	</div>

	<div id = "mateo-container">
		<div id = "mateo"></div>
			<p class = "bio-content"><strong id = "mateo-name">Mateo</strong> is a developer, designer, and explorer, residing in Philadelphia.  He designs apps primarily centered around experiential learning and exploration.  This allows him to bring his knowledge as a teacher, anthropologist, writer, and traveler to people around the world, inspiring them to learn more, live more, experince more, and share the results.</p>
	</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

</div>

schoold/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Schoold</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

  <nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">
        <% if current_user %>
          <%= link_to "Schoold", user_profile_path(current_user.id) %>
        <% else %>  
          <%= link_to "Schoold", root_path %>
        <% end %>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
        <li class="active"><%= link_to "Logout", destroy_user_session_path, method: :delete %><span class="sr-only">(current)</span></a></li>
        <% else %>
        <li class="active"><%= link_to "Login", user_session_path %><span class="sr-only">(current)</span></a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

    <%= yield %>

  </body>
</html>

schoold/app/views/users/profile.html.erb
<div class="row">

  <div class="col-xs-6 bootdiv">.col-xs-6 <!-- Mock Profile -->
  	<p class = "user_pic"><%= image_tag @user.avatar.url(:medium) %></p>

  	<h1 class = "mock_name"></h1>
  	<div class = "badge"></div>
  </div>

  <div class="col-xs-6">.col-xs-6 <!-- Challenge Links -->
    <div class = "custom_background">
    	<h1 class = "challenge_header">The Design Portal</h1>
  <hr>

  	<div class = "top_row">
  		<%= link_to root_path do %>
      <%= image_tag "HTML.jpg", class: "game_pic" %>
  	  	<% end %>

	  	<%= link_to root_path do %>
      <%= image_tag "CSS.jpg", class: "game_pic2" %>
  	  	<% end %>
    	</div>

  	<div class = "bottom_row">
  		<%= link_to root_path do %>
      <%= image_tag "javascript.jpg", class: "game_pic3" %>
  	  	<% end %>

	  	<%= link_to root_path do %>
      <%= image_tag "app_dev.jpg", class: "game_pic4" %>
    		<% end %>
    	</div>

    </div>

  </div>